#$ -t 2-30
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -N rTFM-Test1
#$ -M lorenz.becker@postgrad.manchester.ac.uk
#$ -m ea
module load apps/samtools/1.3.1/gcc-4.8.5+htslib-1.3.2
module load apps/htseq/0.6.1p1/gcc-4.8.5+python-2.7.8+numpy-1.9.2
cd /mnt/mhs01-home01/bk01-icvs/dibb_sparks/mqbprlb2/LKB_RNA/OAv3.1BAMs/
INFILE=$(awk 'NR=='"$SGE_TASK_ID"' {print $1} END {print ""}' OAv3.1BAMs.txt)
if [ -e ${INFILE}.bam ]; then
	samtools view ${INFILE}.bam | htseq-count -r pos -m union - /mnt/mhs01-home01/bk01-icvs/dibb_sparks/mqbprlb2/RefGenomes/OvisAries/OAv3.1/2017-05-29_EalesTranscriptomePrunedOfUnstranded.gtf > ${INFILE}_EalesTrm_RTFM-Pos_Union_stranded.counts
else 
	exit 1
fi

