#$ -t 2-30
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -N cmpSrtBAMNormBAM
#$ -M lorenz.becker@postgrad.manchester.ac.uk
#$ -m ea
cd ~/rds-dibbs-sparks/LKB_RNA/OAv3.1BAMs/
INFILE=$(awk 'NR=='"$SGE_TASK_ID"' {print $1} END {print ""}' OAv3.1BAMs.txt)
if [ -e $INFILE.bam ]; then
	RESULT1=$(~/PhD/tools/BamHash/bamhash_checksum_bam ${INFILE}.bam)
	RESULT2=$(~/PhD/tools/BamHash/bamhash_checksum_bam ${INFILE}.sorted.bam)
	printf "File\tHash\n%s\t%s\n%s\t%s\n" "$INFILE.bam" "$RESULT1" "$INFILE.sorted.bam" "$RESULT2"
else
	exit 1;
fi
