#$ -t 1-1
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -N ExtractBin1Reads
#$ -M lorenz.becker@postgrad.manchester.ac.uk
#$ -m n
module load apps/samtools/1.3.1/gcc-4.8.5+htslib-1.3.2
cd /mnt/mhs01-home01/bk01-icvs/dibb_sparks/mqbprlb2/LKB_RNA/OAv3.1BAMs/
INFILE=$(awk 'NR=='"$SGE_TASK_ID"' {print $1} END {print ""}' OAv3.1BAMs.txt)
if [ -n $INFILE ]; then 
	#samtools sort -@ 8 ${INFILE}.bam -o ${INFILE}.sorted.bam
	#samtools index ${INFILE}.sorted.bam
	samtools view -h -b ${INFILE}.sorted.bam 2:117267199-117314475 > ./BIN1Only/${INFILE}.sorted.BIN1Only.bam
else 
	exit 0
fi