#$ -pe smp.pe 8
#$ -t 1-30
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -N hs2_OAv3.1-RM-LKBv4
#$ -M lorenz.becker@postgrad.manchester.ac.uk
#$ -m ea

module load apps/samtools/1.3.1/gcc-4.8.5+htslib-1.3.2
cd ~/rds-dibbs-sparks/LKB_RNA/Reads/mRNA_gz/

INFILE=$(awk 'BEGIN {FS="[;\t]"} NR=='"$SGE_TASK_ID"' {print "Sample-"$1} END {print ""}' 2017-04-25_AllRNAFiles-GroupedPerSample.txt)
~/PhD/tools/hisat/hisat2 -q --threads "$NSLOTS" -x ~/rds-dibbs-sparks/RefGenomes/OvisAries/hisat/OvsArs-v31-RM -1 $(awk 'BEGIN {FS="[;\t]"} NR=='"$SGE_TASK_ID"' {print ($2"_1.fastq.gz,"$3"_1.fastq.gz," $4"_1.fastq.gz,"$5"_1.fastq.gz")" -2 "($2"_2.fastq.gz,"$3"_2.fastq.gz,"$4"_2.fastq.gz,"$5"_2.fastq.gz") } END {print ""}' 2017-04-25_AllRNAFiles-GroupedPerSample.txt) > ~/scratch/LKB/${INFILE}_OAv3.1-RM_aligned.sam
samtools view -hu ~/scratch/LKB/${INFILE}_OAv3.1-RM_aligned.sam | samtools sort -n -@ $NSLOTS -o ~/scratch/LKB/${INFILE}_OAv3.1-RM_aligned_NameSorted.bam
rm ~/scratch/LKB/${INFILE}_OAv3.1-RM_aligned.sam
