#$ -pe smp.pe 8
#$ -t 1-5
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -N hisat2_OAv3.1_Align-LKB
#$ -M lorenz.becker@postgrad.manchester.ac.uk
#$ -m ea
module load apps/samtools/1.3.1/gcc-4.8.5+htslib-1.3.2
cd ~/PhD/LKB_RNA/RNA_gz/
OUTFILE=$(awk 'BEGIN {FS="[;\t]"} NR=='"$SGE_TASK_ID"' {print "Sample"$1"_"$2} END {print ""}' 2017-04-25_AllRNAFiles-GroupedPerSample.txt)
~/PhD/tools/hisat/hisat2 -q --threads "$NSLOTS" -x ~/PhD/RefGenomes/OvisAries/hisat/OvsArs-v31 -1 $(awk 'BEGIN {FS="[;\t]"} NR=='"$SGE_TASK_ID"' {print ($3"_1.fastq.gz," $4"_1.fastq.gz," $5"_1.fastq.gz")" -2 "($3"_2.fastq.gz,"  $4"_2.fastq.gz," $5"_2.fastq.gz") } END {print ""}' 2017-04-25_AllRNAFiles-GroupedPerSample.txt) > ~/scratch/${OUTFILE}_OAv3.1_aligned.sam
samtools view -hu ~/scratch/${OUTFILE}_OAv3.1_aligned.sam | samtools sort -n -@ $NSLOTS -o ~/scratch/${OUTFILE}_OAv3.1_aligned.bam
rm ~/scratch/${OUTFILE}_OAv3.1_aligned.sam
