#$ -pe smp.pe 4
#$ -l 's_rt=00:30:00'
#$ -t 1-24
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -N hisat2AlignallBHB
#$ -M lorenz.becker@postgrad.manchester.ac.uk
#$ -m bae
cd ~/PhD/BHB_RNA/
~/PhD/tools/hisat/hisat2 -q --threads 4 -x ~/PhD/RefGenomes/OvisAries/hisat/OvsArs -1 `awk 'BEGIN {FS="[;\t]"} NR=='"$SGE_TASK_ID"' {print ($3"_1.fastq.gz," $4"_1.fastq.gz," $5"_1.fastq.gz")" -2 "($3"_2.fastq.gz," $4"_2.fastq.gz," $5"_2.fastq.gz")" -S ~/scratch/Sample"$1"_"$2".sam"} END {print ""}' bundled.txt`
