#!/bin/bash
ts() { date +"%Y-%m-%d_%H-%M-%S"; }
echo $(ts) ": Loading standard RNA-seq libaries..."

OLDPATH=$PATH

#Yes this is technically a bad idea as it modifies $PATH and other environmental variables
/usr/bin/modulecmd bash load apps/binapps/blast/blast+/2.4.0 1>/dev/null
echo "Loaded blast+ v2.4.0..."
/usr/bin/modulecmd bash load apps/binapps/fastqc/0.11.3 1>/dev/null
echo "Loaded fastqc v0.11.3..."
/usr/bin/modulecmd bash load apps/gcc/R/3.3.0 1>/dev/null
echo "Loaded R v3.3.0..."
/usr/bin/modulecmd bash load apps/binapps/tophat/2.0.9 1>/dev/null
echo "Loaded tophat/2.0.9..."
/usr/bin/modulecmd bash load apps/gcc/samtools/1.3.1 1>/dev/null
echo "Loaded samtools/1.3.1"
echo $(ts) ": All modules loaded."
