#$ -t 1-30
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -N hC_OAv3_ENSEMBL_Union
#$ -M lorenz.becker@postgrad.manchester.ac.uk
#$ -m ea
module load apps/htseq/0.6.1p1/gcc-4.8.5+python-2.7.8+numpy-1.9.2
module load apps/samtools/1.3.1/gcc-4.8.5+htslib-1.3.2
cd ~/rds-dibbs-sparks/LKB_RNA/OAv3.1BAMs/
INFILE=$(awk 'NR=='"$SGE_TASK_ID"' { print $1; }' OAv3.1BAMs-v4.txt)

if [ -e ${INFILE}.bam ]; then
	samtools view ${INFILE}.bam | htseq-count --order=name --mode=union --stranded=reverse - ~/rds-dibbs-sparks/RefGenomes/OvisAries/OAv3.1/Ovis_aries.Oar_v3.1.88.gtf > ${INFILE}_ENSEMBL_Union_RevStranded.counts
else
	exit 1
fi
